name: PR

on:
  pull_request_target:
    types: [opened, synchronize]
  pull_request:
    branches:
    - 'main'
  workflow_dispatch:
    
jobs:
  runPR:
    runs-on: ubuntu-latest
    environment: frogbot

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
          
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: FrogBot
      uses: jfrog/frogbot@v2.8.4
      env:
        JF_URL: ${{ secrets.JF_URL }}
        JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
        JF_GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         JF_INCLUDE_ALL_VULNERABILITIES: "TRUE"
#         JF_FAIL: "FALSE"
